### ISSUE TITLE
Allow admins to use script

### ISSUE THREAD

**Issue by enterprisey** [wikimedia-gadgets/afch-rewrite#130]
Just like AWB does. See https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation/2020_1#Can_we_get_the_warning_notice_removed_for_admins%3F.

**Comment by primefac** [comment]
Definitely reasonable. Would also make list maintenance easier.

**Comment by enterprisey** [comment]
@Umang03, would this be fine?

**Comment by Umang03** [comment]
yes @enterprisey  this would be fine .

**Comment by Umang03** [comment]
plz assign this to me .

**Comment by NovemLinguae** [comment]
An admin reports that the recent patch for this didn't work. This may need further tweaking.

> The new version to let admins use afch didn't work, at least for me. I reverted to the previous version --DGG

https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#participant_list

**Comment by siddharthvp** [comment]
Looks to have worked alright after caches expired.
