### ISSUE TITLE
Declining for copyvio AND not selecting G12 should still display copvyio URL on draft

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afch-rewrite#202]
URL is displayed in `{{AFC submission|d|cv` if user checks the "delete" check box (which is correct behavior), but is not displayed if the check box is not checked (this appears to be a bug)

Reported by Gpkp. Discussion at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFCH_reviews

Possible culprit is at https://github.com/WPAFC/afch-rewrite/blob/master/src/modules/submissions.js#L2329

**Comment by primefac** [comment]
Can we make this a high(er) priority? It's seriously messing with the ability to review declined drafts.

**Comment by NovemLinguae** [comment]
Duplicate of #221. Closing.
