### ISSUE TITLE
Color code AFC comments depending on decline or regular comment

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afch-rewrite#222]
Requested by DoubleGrazing at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#AFCH_Tool_Wish_List

Suggests color coding the exclamation mark of the {{AfC comment}} template depending on whether it's a decline or a regular comment.

![image](https://user-images.githubusercontent.com/79697282/158010307-2012d754-344e-4a20-a46c-221545061edd.png)

**Comment by primefac** [comment]
I'll have to think about it more, but I feel like this would be best/easiest achieved by adding in an #if statement to the template itself, and then have the script trigger that #if for comments placed as a result of a decline.
