### ISSUE TITLE
Heading at bottom of article incorrectly deleted

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afch-rewrite#234]
Reported by DoubleGrazing at https://en.wikipedia.org/wiki/Wikipedia_talk:WikiProject_Articles_for_creation#Rejection_removed_content

Diff: https://en.wikipedia.org/w/index.php?title=User:Abhaysen830/sandbox&diff=next&oldid=1090566900

Does AFC have code that tries to delete headings at the bottom of an article that begin with the draft name? I know the AFC submit wizard or some other workflow appends a heading with the article name and the AFC submission template, resulting in extra headings. Perhaps AFCH tries to delete this extra heading, and was overly broad here.

Another possibility is an overly broad regex.

![image](https://user-images.githubusercontent.com/79697282/170934950-cdbfbc29-9f24-42d6-8ecd-63222112fadc.png)

**Comment by primefac** [comment]
This is a GIGO issue; the script removes extraneous headings from the bottom of articles, and the fact that someone put their entire draft _in_ the header is their fault, not ours. Not that it is strictly the reviewer's fault for not doing so, but they should have removed the header code before rejecting the draft.

**Comment by NovemLinguae** [comment]
Abandoning. Received pushback.
