### ISSUE TITLE
Move repo to wikimedia-gadgets organisation?

### ISSUE THREAD

**Issue by siddharthvp** [wikimedia-gadgets/afch-rewrite#244]
Since the parent org (WPAFC) doesn't have any other active repos (and hasn't had any for years), I wonder if we should move this over to wikimedia-gadgets org? There it will join twinkle, xfdcloser, moremenu and other actively maintained projects. 

(All current users with merge access will continue to have access, even if they are not a member of wikimedia-gadgets.)

**Comment by enterprisey** [comment]
works for me, might as well leave it for a bit (week?) for any potential objections

**Comment by siddharthvp** [comment]
@enterprisey it's been a week :)

**Comment by enterprisey** [comment]
sure has been

**Comment by enterprisey** [comment]
Done, I think. Let me know if anything else needs clicking.

**Comment by NovemLinguae** [comment]
I think @IngenuityWP lost access. Is there a way to add them as a collaborator? May need to add all the old WPAFC members as collaborators as well.

**Comment by siddharthvp** [comment]
Hmm, when twinkle was migrated here, all existing collaborators were automatically grandfathered. That doesn't seem to have happened in this case. Anyway, I see Ingenuity has already been invited as collaborator.

**Comment by NovemLinguae** [comment]
Perhaps collaborators get moved over but members don't. I think AFCH mostly used members. So it may be a good idea to peek at the member list and invite those folks as collaborators. Hope this helps.

**Comment by siddharthvp** [comment]
Yeah that must be it. I've sent invites to everyone on WPAFC member list who isn't a member here, though they're all inactive so not sure how many responses we get.
