### ISSUE TITLE
very long load time of AFCH started via `npm start` on testwiki

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afch-rewrite#267]
Had to click through like 5 of these "Page Unresponsive" dialogs to get it to do anything. F12 devtools wouldn't open until the very end. Took several minutes.

Declining a draft, same thing.

Any ideas how to troubleshoot?

https://test.wikipedia.org/wiki/Draft:Test

https://test.wikipedia.org/wiki/User:Novem_Linguae/common.js

<img width="906" alt="image" src="https://github.com/wikimedia-gadgets/afch-rewrite/assets/79697282/0eedb234-9f56-47c4-8096-46f958807964">

<img width="960" alt="image" src="https://github.com/wikimedia-gadgets/afch-rewrite/assets/79697282/81d63a5c-6765-4e10-a881-bf92ddf91d3e">

<img width="887" alt="image" src="https://github.com/wikimedia-gadgets/afch-rewrite/assets/79697282/cff4b6da-69a9-42ba-9649-7e6f15a58fe7">

**Comment by KylieTastic** [comment]
Is this not the same issue as #245 ?

**Comment by NovemLinguae** [comment]
Nailed it. Thank you @KylieTastic. I will edit https://test.wikipedia.org/wiki/Draft:Test to not contain this wikicode that triggers the other issue.
