### ISSUE TITLE
remove unused dev dependencies

### ISSUE THREAD

**Issue by NovemLinguae** [wikimedia-gadgets/afch-rewrite#273]
I need someone to double check me on this, but a quick search of the codebase suggests that the dependency minimist is not used at all and can be removed from package.json:

* minimist - "parse argument options. This module is the guts of optimist's argument parser without all the fanciful decoration." Not sure what this means.
* ~~jquery - Is this needed? MediaWiki provides jquery.~~

**Comment by siddharthvp** [comment]
minimist is a parser for command line arguments passed when you invoke a node script. It may have been used at some point for one of the dev scripts.

jQuery is for the unit testing setup (although we should ideally use mock-mediawiki).
